stages:
- type: docker-build
  name: build
  dockerfile: soeom/docker
- name: push
  type: docker-push
  from_stage: build
  repo: j18e/ci-test-1
  tags:
  - $KUBELINE_GIT_BRANCH
  - $KUBELINE_GIT_COMMIT_SHORT
