stages:
- type: docker-build
  name: build
- type: custom
  name: randomstuff
  image: alpine
  commands:
  - echo doing stuff
  - ls -l
  - cat Dockerfile
- name: push
  type: docker-push
  from_stage: build
  repo: j18e/ci-test-1
  tags:
  - $KUBELINE_GIT_BRANCH
  - $KUBELINE_GIT_COMMIT_SHORT
