stages:
- name: test
  type: custom
  image: python:3-alpine
  commands:
  - python code.py
- name: build
  type: docker-build
- name: push
  type: docker-push
  from_stage: build
  repo: j18e/ci-test-1
  tags:
  - $KUBELINE_GIT_BRANCH-$KUBELINE_ITERATION
  - $KUBELINE_GIT_COMMIT_SHORT
